//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASCOM.DirectShow.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreferredCaptureDevice {
            get {
                return ((string)(this["PreferredCaptureDevice"]));
            }
            set {
                this["PreferredCaptureDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Uncompressed")]
        public string PreferredCompressorDevice {
            get {
                return ((string)(this["PreferredCompressorDevice"]));
            }
            set {
                this["PreferredCompressorDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Color")]
        public global::ASCOM.DirectShow.VideoFrameLayout SimulatedImageLayout {
            get {
                return ((global::ASCOM.DirectShow.VideoFrameLayout)(this["SimulatedImageLayout"]));
            }
            set {
                this["SimulatedImageLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public global::ASCOM.DirectShow.MonochromePixelMode MonochromePixelsType {
            get {
                return ((global::ASCOM.DirectShow.MonochromePixelMode)(this["MonochromePixelsType"]));
            }
            set {
                this["MonochromePixelsType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsesTunerCrossbar {
            get {
                return ((bool)(this["UsesTunerCrossbar"]));
            }
            set {
                this["UsesTunerCrossbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CrossbarOutputPin {
            get {
                return ((int)(this["CrossbarOutputPin"]));
            }
            set {
                this["CrossbarOutputPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CrossbarInputPin {
            get {
                return ((int)(this["CrossbarInputPin"]));
            }
            set {
                this["CrossbarInputPin"] = value;
            }
        }
    }
}
